class DailyWorkModel {
  String id,
      lightsCondition,
      oFansCondition,
      heatersCondition,
      eFansCondition,
      dehumidifierCondition,
      acCondition,
      tHigh,
      tLow,
      hHigh,
      hLow,
      feed,
      flush,
      gPlant,
      administrationPlant,
      fBuggySpray,
      fRinse,
      fFoodSpray,
      aSpray,
      bugs,
      waterORSoilTreatment,
      transplanting,
      topping,
      pruning,
      staking,
      cloning,
      harvest,
      cleaning,
      maintenance,
      construction,
      notes,
      createdAt,
      totalHours,
      createdBy;

  DailyWorkModel(
      {this.id,
      this.lightsCondition,
      this.oFansCondition,
      this.heatersCondition,
      this.eFansCondition,
      this.dehumidifierCondition,
      this.acCondition,
      this.tHigh,
      this.tLow,
      this.hHigh,
      this.hLow,
      this.feed,
      this.flush,
      this.gPlant,
      this.administrationPlant,
      this.fBuggySpray,
      this.fRinse,
      this.fFoodSpray,
      this.aSpray,
      this.bugs,
      this.waterORSoilTreatment,
      this.transplanting,
      this.topping,
      this.pruning,
      this.staking,
      this.cloning,
      this.harvest,
      this.cleaning,
      this.maintenance,
      this.construction,
      this.notes,
      this.createdAt,
      this.totalHours,
      this.createdBy});

  factory DailyWorkModel.fromJson(Map<String, dynamic> json) {
    return new DailyWorkModel(
        id: json['_id'].toString(),
        lightsCondition: json['LightsCondition'].toString(),
        oFansCondition: json['OFansCondition'].toString(),
        heatersCondition: json['HeatersCondition'].toString(),
        eFansCondition: json['EFansCondition'].toString(),
        dehumidifierCondition: json["DehumidifierCondition"].toString(),
        acCondition: json["AcCondition"].toString(),
        tHigh: json["THigh"].toString(),
        tLow: json["TLow"].toString(),
        hHigh: json["HHigh"].toString(),
        hLow: json["HLow"].toString(),
        feed: json["Feed"].toString(),
        flush: json["Flush"].toString(),
        gPlant: json["GPlant"].toString(),
        administrationPlant: json["AdministrationPlant"].toString(),
        fBuggySpray: json["FBuggySpray"].toString(),
        fRinse: json["FRinse"].toString(),
        fFoodSpray: json["FFoodSpray"].toString(),
        aSpray: json["ASpray"].toString(),
        bugs: json["Bugs"].toString(),
        waterORSoilTreatment: json["WaterORSoilTreatment"].toString(),
        transplanting: json["Transplanting"].toString(),
        topping: json["Topping"].toString(),
        pruning: json["Pruning"].toString(),
        staking: json["Staking"].toString(),
        cloning: json["Cloning"].toString(),
        harvest: json["Harvest"].toString(),
        cleaning: json["Cleaning"].toString(),
        maintenance: json["Maintenance"].toString(),
        construction: json["Construction"].toString(),
        notes: json["Notes"].toString(),
        createdAt: json["CreatedAt"].toString(),
        totalHours: json["TotalHours"].toString(),
        createdBy: json["CreatedBy"].toString());
  }
}
